### ISSUE TITLE
y-axis units

### ISSUE THREAD

**Issue by Dieterbe** [grafana/heatmap-panel#1]
similar to graph panels, would be nice if i could specify the unit of the buckets (e.g. y-axis). and even better would be if it could automatically convert (like the graph panel)
for example now i see buckets 1000, 15000, .... 6000. those are in ms. would be nice if that showed as 1s, 1.5s ... 6s

**Comment by alexanderzobnin** [comment]
Closed by ba2672328391cc8d88809d99435ad2e32ae78fe1
